homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
]

mortgage/urls.py
from django.urls import path

from . import views

app_name = 'mortgage'

urlpatterns = [
    path('', views.mortgage_calculator, name='mortgage_calculator'),
    path('calculations/', views.calculation_list, name='calculation_list'),
    path('calculations/<int:pk>/', views.calculation_detail, name='calculation_detail'),
]

property/urls.py
from django.urls import path
from . import views

app_name = 'property'

urlpatterns = [
    path('', views.PropertyListView.as_view(), name='list'),
    path('create/', views.PropertyCreateView.as_view(), name='create'),
    path('<int:pk>/', views.PropertyDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', views.PropertyUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.PropertyDeleteView.as_view(), name='delete'),
]

real_estate_investing/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('property/', include('property.urls', namespace='property')),
    path('api/', include('property.api_urls')),
    path('mortgage/', include('mortgage.urls', namespace='mortgage')),
    path('trench-mortgage/', include('trench_mortgage.urls', namespace='trench_mortgage')),
]

trench_mortgage/urls.py
from django.urls import path
from . import views

app_name = 'trench_mortgage'

urlpatterns = [
    path('', views.trench_mortgage_calculator, name='trench_mortgage_calculator'),
    path('calculate/', views.calculate_trench_mortgage, name='calculate_trench_mortgage'),
]

templates/includes/footer.html
<footer>
    <p>Pavel Murlykin, 2025</p>
</footer>

templates/includes/header.html
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <div class="navbar-nav">
                <a class="nav-link" href="{% url 'homepage:index' %}">Главная</a>
                <a class="nav-link" href="{% url 'property:list' %}">Объекты недвижимости</a>
                <a class="nav-link" href="{% url 'mortgage:mortgage_calculator' %}">Ипотечный калькулятор</a>
                <a class="nav-link" href="{% url 'trench_mortgage:trench_mortgage_calculator' %}">Траншевая ипотека</a>
            </div>
        </div>
    </nav>
</header>